### ISSUE TITLE
Nitro api client timing out

### ISSUE THREAD

**Issue by sanket4373** [slauger/python-nitro#1]
I am trying to use your client to run some commands on my netscaler. Have sourced the login creds from my config file `ns.conf`

```
(pywork) ➜  python-nitro git:(master) ./cli.py --config ~/.config/ns.conf get config nsversion
Traceback (most recent call last):
  File "./cli.py", line 130, in <module>
    params=args.params
  File "/Users/srlawang/workspace/netscalers/python-nitro/nitro.py", line 61, in request
    verify=self._verify,
  File "/Users/srlawang/.virtualenv/pywork/lib/python2.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/srlawang/.virtualenv/pywork/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/srlawang/.virtualenv/pywork/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/srlawang/.virtualenv/pywork/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Users/srlawang/.virtualenv/pywork/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='xx.xx.xx.xx', port=80): Max retries exceeded with url: /nitro/v1/config/nsversion (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x105cef9d0>: Failed to establish a new connection: [Errno 60] Operation timed out',))
```

I also verified against the api reference document to be sure that the call `url: /nitro/v1/config/nsversion` is indeed correct :  https://developer-docs.citrix.com/projects/netscaler-nitro-api/en/12.0/configuration/ns/nsversion/nsversion/#get-all

I am not sure what i might have missed here? Or if it is a python version error?

**Comment by slauger** [comment]
This looks more like a firewall or proxy (ENV `http_proxy`) problem. Are you able to connect via `curl`? Maybe HTTP (plaintext) is disabled on your NetScaler. Try a connection with HTTPS instead and see what happens.

```
-bash$ ./cli.py --config ~/.config/ns.conf get config nsversion
{u'errorcode': 0, u'message': u'Done', u'severity': u'NONE', u'nsversion': {u'installedversion': False, u'version': u'NetScaler NS13.0: Build 36.27.nc, Date: May 13 2019, 11:42:13   (64-bit)', u'mode': u'1'}}
```

Tested with Python 2.7.16 on OSX.
